[build]
  publish = "."

[[redirects]]
  from = "/success"
  to = "/success/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/success/"
  to = "/success/index.html"
  status = 200
  force = true